services:
  app:
    build: .
    working_dir: /app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DSN=postgresql+psycopg2://postgres:password@db:5432/finstat
    depends_on:
      - db
    volumes:
      - ./AWS/app:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finstat
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: